import type { SocialPlatform } from './types';

export const SOCIAL_PLATFORMS: SocialPlatform[] = [
  // === Social ===
  {
    id: 'x-platform',
    name: 'X',
    label: 'X PLATFORM',
    icon: 'x',
    color: '#000000',
    bgColor: '#1a1a1a',
    category: 'social',
    description: 'Post, engage, and grow your audience on X',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    label: 'INSTAGRAM',
    icon: 'instagram',
    color: '#E1306C',
    bgColor: '#1a0a12',
    category: 'social',
    description: 'Share photos, stories, and reels',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    label: 'FACEBOOK',
    icon: 'facebook',
    color: '#1877F2',
    bgColor: '#0a1529',
    category: 'social',
    description: 'Connect with friends and communities',
  },
  {
    id: 'threads',
    name: 'Threads',
    label: 'THREADS',
    icon: 'threads',
    color: '#FFFFFF',
    bgColor: '#1a1a1a',
    category: 'social',
    description: 'Join text-based conversations',
  },
  {
    id: 'bluesky',
    name: 'Bluesky',
    label: 'BLUESKY',
    icon: 'bluesky',
    color: '#0085FF',
    bgColor: '#0a1525',
    category: 'social',
    description: 'Decentralized social networking',
  },
  {
    id: 'mastodon',
    name: 'Mastodon',
    label: 'MASTODON',
    icon: 'mastodon',
    color: '#6364FF',
    bgColor: '#12122a',
    category: 'social',
    description: 'Open-source federated social network',
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    label: 'SNAPCHAT',
    icon: 'snapchat',
    color: '#FFFC00',
    bgColor: '#1a1a0a',
    category: 'social',
    description: 'Share moments with friends via snaps',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    label: 'REDDIT',
    icon: 'reddit',
    color: '#FF4500',
    bgColor: '#1a0e0a',
    category: 'social',
    description: 'Engage with niche communities',
  },

  // === Video ===
  {
    id: 'youtube',
    name: 'YouTube',
    label: 'YOUTUBE',
    icon: 'youtube',
    color: '#FF0000',
    bgColor: '#1a0a0a',
    category: 'video',
    description: 'Upload and manage video content',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    label: 'TIKTOK',
    icon: 'tiktok',
    color: '#00F2EA',
    bgColor: '#0a1a1a',
    category: 'video',
    description: 'Create and share short-form videos',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    label: 'TWITCH',
    icon: 'twitch',
    color: '#9146FF',
    bgColor: '#150f29',
    category: 'video',
    description: 'Stream live content to your audience',
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    label: 'VIMEO',
    icon: 'vimeo',
    color: '#1AB7EA',
    bgColor: '#0a1520',
    category: 'video',
    description: 'Host and share professional video content',
  },

  // === Professional ===
  {
    id: 'linkedin',
    name: 'LinkedIn',
    label: 'LINKEDIN',
    icon: 'linkedin',
    color: '#0A66C2',
    bgColor: '#0a1220',
    category: 'professional',
    description: 'Build your professional network',
  },
  {
    id: 'github',
    name: 'GitHub',
    label: 'GITHUB',
    icon: 'github',
    color: '#FFFFFF',
    bgColor: '#1a1a1a',
    category: 'professional',
    description: 'Collaborate on code repositories',
  },
  {
    id: 'medium',
    name: 'Medium',
    label: 'MEDIUM',
    icon: 'medium',
    color: '#FFFFFF',
    bgColor: '#1a1a1a',
    category: 'professional',
    description: 'Publish articles and thought leadership',
  },
  {
    id: 'substack',
    name: 'Substack',
    label: 'SUBSTACK',
    icon: 'substack',
    color: '#FF6719',
    bgColor: '#1a100a',
    category: 'professional',
    description: 'Build and grow your newsletter',
  },

  // === Messaging ===
  {
    id: 'discord',
    name: 'Discord',
    label: 'DISCORD',
    icon: 'discord',
    color: '#5865F2',
    bgColor: '#101229',
    category: 'messaging',
    description: 'Manage communities and servers',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    label: 'TELEGRAM',
    icon: 'telegram',
    color: '#26A5E4',
    bgColor: '#0a1520',
    category: 'messaging',
    description: 'Broadcast messages and manage channels',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    label: 'WHATSAPP',
    icon: 'whatsapp',
    color: '#25D366',
    bgColor: '#0a1a10',
    category: 'messaging',
    description: 'Connect via WhatsApp Business API',
  },
  {
    id: 'slack',
    name: 'Slack',
    label: 'SLACK',
    icon: 'slack',
    color: '#4A154B',
    bgColor: '#1a0a1a',
    category: 'messaging',
    description: 'Integrate with workspace channels',
  },

  // === Creative ===
  {
    id: 'pinterest',
    name: 'Pinterest',
    label: 'PINTEREST',
    icon: 'pinterest',
    color: '#E60023',
    bgColor: '#1a0a0e',
    category: 'creative',
    description: 'Share pins and visual inspiration',
  },
  {
    id: 'dribbble',
    name: 'Dribbble',
    label: 'DRIBBBLE',
    icon: 'dribbble',
    color: '#EA4C89',
    bgColor: '#1a0a14',
    category: 'creative',
    description: 'Showcase design work and projects',
  },
  {
    id: 'behance',
    name: 'Behance',
    label: 'BEHANCE',
    icon: 'behance',
    color: '#1769FF',
    bgColor: '#0a1229',
    category: 'creative',
    description: 'Display your creative portfolio',
  },
  {
    id: 'figma',
    name: 'Figma',
    label: 'FIGMA',
    icon: 'figma',
    color: '#F24E1E',
    bgColor: '#1a0e0a',
    category: 'creative',
    description: 'Collaborate on design files and prototypes',
  },

  // === Music ===
  {
    id: 'spotify',
    name: 'Spotify',
    label: 'SPOTIFY',
    icon: 'spotify',
    color: '#1DB954',
    bgColor: '#0a1a10',
    category: 'music',
    description: 'Share music and podcast content',
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud',
    label: 'SOUNDCLOUD',
    icon: 'soundcloud',
    color: '#FF5500',
    bgColor: '#1a0f0a',
    category: 'music',
    description: 'Upload and distribute audio content',
  },

  // === Commerce ===
  {
    id: 'shopify',
    name: 'Shopify',
    label: 'SHOPIFY',
    icon: 'shopify',
    color: '#96BF48',
    bgColor: '#141a0a',
    category: 'commerce',
    description: 'Manage your e-commerce storefront',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    label: 'STRIPE',
    icon: 'stripe',
    color: '#635BFF',
    bgColor: '#100f29',
    category: 'commerce',
    description: 'Process payments and manage subscriptions',
  },

  // === Productivity ===
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    label: 'GOOGLE SHEETS',
    icon: 'google-sheets',
    color: '#0F9D58',
    bgColor: '#0a1a10',
    category: 'productivity',
    description: 'Read and write spreadsheet data',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'social', label: 'Social' },
  { id: 'video', label: 'Video' },
  { id: 'professional', label: 'Professional' },
  { id: 'messaging', label: 'Messaging' },
  { id: 'creative', label: 'Creative' },
  { id: 'music', label: 'Music' },
  { id: 'commerce', label: 'Commerce' },
  { id: 'productivity', label: 'Productivity' },
] as const;
